# ignore_drafts: true
# 网站标题
title: 水桶的小屋
# 网站标题后缀
suffix: .Backup
# 作者名称
author: 可能是水桶吧
# 网站关键字
keyword: 技术,美术,Blender,C4D,AE
#false是否开启文章背景图显示(随机图片)
is_article_img: true  
# 网站描述
web_description: 一些自己存在过的记录
# 首页文章布局 默认 'card' 可选择 'block-card'
home_layout: card
# 导航名称
menus_title:
  home: 封面
  fav: 快速文档
  categories: 分栏
  tags: 标记
  archive: 时间线
  links: 外链
  about: 关于我
# 导航 （不建议修改）
menus:
  home: /
  fav: /tags/快速文档
  categories: /categories
  tags: /tags
  archive: /archives
  links: /links
  about: /about
  
# logo
logo: /assets/blog/about/d.webp.jpg
# 网页标签上那个小图标 一定要用本地存储
icon: /assets/blog/about/d.webp.jpg
# 每个页面的展示的图标和一句话
headers:
    home: {
      message: "时间以同样的方式流经每个人",
      icon: "/assets/blog/about/d.webp.jpg"
    }
    archives: {
      # 这里会替换掉两个变量{ year 年，number 总数 } 当然也可以不写这两个变量
      message: "从昼夜启始到这里，year 年，number 步",
      icon: "/assets/website/archive.png"
    }
    tags: {
      message: "标签是孤品",
      icon: "/assets/website/tag.png"
    }
    links: {
      message: "一些流淌的痕迹",
      icon: "/assets/website/project.png"
    }
    categories: {
      message: "无聊时的方向",
      icon: "/assets/website/category.png"
    }
# 网页访问统计
# web_analytics:  
#   enable: false #需要改为true
#   baidu: 4b5fe1472f22fadsfs  # （替换）百度统计的 Key，参见 https://tongji.baidu.com/sc-web/10000033910/home/site/getjs?siteId=13751376 代码获取中 hm.js? 后边的字符串
# 评论 
# gitalk:
#   clientID: 02b3c # （需要替换）GitHub Application Client ID.
#   clientSecret: adfc7b4 #（需要替换）GitHub Application Client Secret.
#   repo: gimment #（需要替换）GitHub repository.
#   owner: duneng #（需要替换）GitHub repository 所有者，可以是个人或者组织。
#   admin: ['duneng'] #（需要替换）GitHub repository 的所有者和合作者 (对这个 repository 有写权限的用户)。

# 底部显示的图标（github 或者其他）
bottomIcon: 
  #可以多个
  - {
    #描述名称
    name: 'Zcool',
    #图标    
    iconLink: '/assets/website/zcool-icon2.png',
    #跳转链接    
    toUrl: 'https://visnz.zcool.com.cn/'
  }
  - {
    #描述名称
    name: '小红书',
    #图标    
    iconLink: '/assets/website/xhs-icon.png',
    #跳转链接    
    toUrl: 'https://www.xiaohongshu.com/user/profile/599e99f650c4b40fb927384f'
  }
  - {
    #描述名称
    name: 'Bilibili',
    #图标    
    iconLink: '/assets/website/bilibili-icon.png',
    #跳转链接    
    toUrl: 'https://space.bilibili.com/20477830'
  }
  - {
    #描述名称
    name: 'QQ',
    #图标    
    iconLink: '/assets/website/QQ-icon.png',
    #跳转链接    
    toUrl: '/assets/blog/about/QQ_QRCode.jpg'
  }
# 友情链接
linksList:
  - {
    title: 'Blender插件：快照',
    intro: '含文件快访/小工具箱',
    link: 'https://github.com/visnz/Snapshot_3d_viewer',
    image: '/assets/website/blender.png'
  }
  - {
    title: '随机词汇生成器',
    intro: '抽象工具',
    link: 'https://github.com/visnz/RandomWordsGen',
    image: '/assets/website/python.png'
  }
  - {
    title: '屏幕定时截图',
    intro: '用截图替代录屏',
    link: 'https://github.com/visnz/screenshot-sh',
    image: '/assets/website/python.png'
  }

#默认的cover (默认缩略图) 在没有填写（这里可以替换（可以是api也可以是固定的图））
# https://api.ixiaowai.cn/gqapi/gqapi.php
# https://tuapi.eees.cc/api.php?type=302&category=fengjing
default_cover: /assets/blog/about/d.webp.jpg #/assets/blog/2024/OSLnote/title.png
# categories:
#   CG通用相关: '/assets/categories/CG通用相关.png'
#   读书笔记: '/assets/categories/读书笔记.png'
#   工具与其他: '/assets/categories/工具与其他.png'
#   年终回顾: '/assets/categories/年终回顾.png'